### ISSUE TITLE
Request/Question: Getting content to span across two columns

### ISSUE THREAD

**Issue by willmruzek** [jh3y/driveway#12]
Hello,

First, thank you for creating this. Working with it has been insightful.

I wondered if it were possible to have content span across two columns rather than being constrained to the number columns used per viewport width.

Thanks!

**Comment by jh3y** [comment]
Hey @mruzekw ,

Sorry for the delayed response and thanks for the kind words! :smile:

That's a good question. Unfortunately I don't think the spec allows specifying the amount of columns an item can span :cry: The supported values are `1(_default_)`, `inherit`, `initial` and `all`.

`all` would allow an item to span multiple columns at once but that item will span all columns (_It's also worth nothing that the `column-span` property is not supported in `Firefox`._)

@jh3y
