### ISSUE TITLE
PLEASE add info about browser compatibility

### ISSUE THREAD

**Issue by COLABORATI** [jh3y/driveway#4]
OK, this is an impressive piece of work, however the information I was looking for in the first place was the answer to the question "which browsers does this support?". Please add this very important information on top of the readme, thank you very much!

**Comment by jh3y** [comment]
Hi @COLABORATI 

That's not a bad idea to be honest. Maybe a small table to indicate this will suffice? It seems to work for me in `IE10+` and there are no apparent issues in other browsers.

Something like:

### Browser support

| Chrome | Firefox | Safari | Opera | Edge | IE |
| --- | :-: | --: | --- | --- | --- |
| :smile: | :smile: | :smile: | :smile: | :smile: | :sweat:* |

***** _`driveway` will play nice in `IE10+`_

I'll add that in for now and see if that helps people. `driveway` only really worries about multi column layout CSS properties and flexbox and that should cover it :smile: 

@jh3y
