### ISSUE TITLE
Direction

### ISSUE THREAD

**Issue by malfborger** [jh3y/driveway#7]
Is there some way to change direction left to right so that you can have a feed chronologically. e.g newsfeed.

**Comment by jh3y** [comment]
Hey @malfborger 

Unfortunately, this doesn't seem to be possible with purely CSS. The best solution could be to use a JavaScript workaround or maybe a server side rendering solution.

I've discussed this issue in the `README` [here](https://github.com/jh3y/driveway#timeline-ordering-issue).

Hope that helps a little :smile:

**Comment by jh3y** [comment]
Duplicate of #1
