### ISSUE TITLE
Order columns items

### ISSUE THREAD

**Issue by chemitaxis** [jh3y/driveway#9]
### issue summary
Order different like masonry. The items is attached to the DOM in Column1 and down, Column2 and down

### expected behavior
First item must be the first in the first column (ok) , second item -> first item in the second colum (bad)

### browser used
Chrome, Safari, Firefox

Thanks!!

**Comment by jh3y** [comment]
Hey @chemitaxis 

If I'm right in thinking you're referring to being able to order content from left to right whilst keeping it masonry. Unfortunately, as far as I'm currently aware, this is __not__ possible with purely CSS.

To achieve the desired effect would require intervention from either JavaScript or possibly a server-side rendering solution. I've touched on this [here](https://github.com/jh3y/driveway#timeline-ordering-issue). However, if you do have a solution to this, please feel free to open a PR! I'd love to see a solution :smile:

Thanks!

@jh3y

**Comment by chemitaxis** [comment]
Oh! Thanks! SO fast!! 👍  I will check the link!!
